name: trendify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6
  
  google_fonts: ^8.0.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/trendify.png
    - lib/assets/images/homebackground.png
    - lib/assets/images/loginbackground.jpeg
    - lib/assets/images/registerbackground.jpeg
    - lib/assets/images/myprofile.jpeg
    - lib/assets/images/admin.jpeg
    - lib/assets/images/add.jpeg