name: trendify
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
    

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^2.24.0
  cloud_firestore: 4.17.5
  firebase_auth: ^4.6.3
  firebase_storage: ^11.5.1
  google_fonts: ^6.0.0 

   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/trendify.png
    - lib/assets/images/homebackground.png
    - lib/assets/images/loginbackground.jpeg
    - lib/assets/images/registerbackground.jpeg
    - lib/assets/images/myprofile.jpeg
    - lib/assets/images/admin.jpeg
    - lib/assets/images/add.jpeg




  # Assets (slike) – primer
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Fonts – primer
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
